FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake lua5.3 pkg-config meson liblua5.3 liblxi-dev

COPY . /repo
WORKDIR /repo/build
RUN meson ..
RUN ninja
